// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Event struct {
	EventID    int64     `json:"event_id"`
	DeliveryID string    `json:"delivery_id"`
	EventName  string    `json:"event_name"`
	TargetUrl  string    `json:"target_url"`
	BodyJson   string    `json:"body_json"`
	Secret     string    `json:"secret"`
	CreatedAt  time.Time `json:"created_at"`
}
