// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package db

import (
	"context"
	"time"
)

const getEvent = `-- name: GetEvent :one
SELECT
    delivery_id,
    event_name,
    target_url,
    body_json,
    secret, 
    created_at
FROM events
WHERE delivery_id = ?
`

type GetEventRow struct {
	DeliveryID string    `json:"delivery_id"`
	EventName  string    `json:"event_name"`
	TargetUrl  string    `json:"target_url"`
	BodyJson   string    `json:"body_json"`
	Secret     string    `json:"secret"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) GetEvent(ctx context.Context, deliveryID string) (GetEventRow, error) {
	row := q.db.QueryRowContext(ctx, getEvent, deliveryID)
	var i GetEventRow
	err := row.Scan(
		&i.DeliveryID,
		&i.EventName,
		&i.TargetUrl,
		&i.BodyJson,
		&i.Secret,
		&i.CreatedAt,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events (
    delivery_id,
    event_name,
    target_url,
    body_json,
    secret, 
    created_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	DeliveryID string    `json:"delivery_id"`
	EventName  string    `json:"event_name"`
	TargetUrl  string    `json:"target_url"`
	BodyJson   string    `json:"body_json"`
	Secret     string    `json:"secret"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.DeliveryID,
		arg.EventName,
		arg.TargetUrl,
		arg.BodyJson,
		arg.Secret,
		arg.CreatedAt,
	)
	return err
}

const listEvents = `-- name: ListEvents :many
SELECT
    delivery_id,
    event_name,
    target_url,
    body_json,
    secret, 
    created_at
FROM events
ORDER BY created_at DESC
`

type ListEventsRow struct {
	DeliveryID string    `json:"delivery_id"`
	EventName  string    `json:"event_name"`
	TargetUrl  string    `json:"target_url"`
	BodyJson   string    `json:"body_json"`
	Secret     string    `json:"secret"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.DeliveryID,
			&i.EventName,
			&i.TargetUrl,
			&i.BodyJson,
			&i.Secret,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
